org.gradle.jvmargs=-Xmx1G
minecraft_version=1.21.1
neo_version=21.1.169

parchment_mapping_version=2024.11.17
parchment_mc_version=1.21.1

mod_version=1.0.0
maven_group=com.example.exampleaddon
archives_base_name=example-kubejs-addon
mod_id=exampleaddon
mod_name=Example KubeJS Addon
mod_author=YourNameHere

kjs_ver=2101.7.1-build.181
rhino_ver=2101.2.7-build.74
