[plugins]
loom = { id = "dev.architectury.loom", version.ref = "loom" }

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
forge     = { module = "net.minecraftforge:forge", version.ref = "forge" }
kubejs    = { module = "dev.latvian.mods:kubejs-forge", version.ref = "kubejs" }
mixinextras-common = { module = "io.github.llamalad7:mixinextras-common", version.ref = "mixinextras" }
mixinextras-forge  = { module = "io.github.llamalad7:mixinextras-forge", version.ref = "mixinextras" }


[versions]
loom = "1.10-SNAPSHOT"

minecraft   = "1.20.1"
forge       = "1.20.1-47.4.0"
kubejs      = "2001.6.5-build.16"
mixinextras = "0.3.2"
