modLoader = "javafml"
loaderVersion = "[2,)"
license = "All rights reserved" # https://choosealicense.com/


# issueTrackerURL="https://github.com/invalid/pleasechangeme/issues"

[[mods]]
modId = "exampleaddon"
version = "${version}"
displayName = "Example Addon"
logoFile="icon.png"
# credits="Thanks to FooterMan for the KubeJS Addon Template!"
# authors="YourNameHere"
description = '''
Example KubeJS Addon.
'''

[[dependencies.exampleaddon]]
modId = "neoforge"
type = "required"
versionRange = "[21.0.148,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.exampleaddon]]
modId = "kubejs"
type = "required"
versionRange = "[2100.7.0,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "exampleaddon.mixins.json"